/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 05/10/2026 02:17:14          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE 'C:\Users\leand\Desktop\novaselecao\ordens.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_CLIENTE_ID;
SET GENERATOR GEN_CLIENTE_ID TO 4;

CREATE GENERATOR GEN_ITEM_ORDEM_ID;
SET GENERATOR GEN_ITEM_ORDEM_ID TO 7;

CREATE GENERATOR GEN_ORDEM_SERVICO_ID;
SET GENERATOR GEN_ORDEM_SERVICO_ID TO 8;

CREATE GENERATOR GEN_STATUS_LOG_ID;
SET GENERATOR GEN_STATUS_LOG_ID TO 12;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CLIENTE (
    ID            INTEGER NOT NULL,
    NOME          VARCHAR(120) NOT NULL,
    DOCUMENTO     VARCHAR(20),
    EMAIL         VARCHAR(120),
    TELEFONE      VARCHAR(30),
    DATACADASTRO  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ITEM_ORDEM (
    ID              INTEGER NOT NULL,
    ORDEM_ID        INTEGER NOT NULL,
    DESCRICAO       VARCHAR(200) NOT NULL,
    QUANTIDADE      NUMERIC(12,2) NOT NULL,
    VALOR_UNITARIO  NUMERIC(15,2) NOT NULL
);

CREATE TABLE ORDEM_SERVICO (
    ID                  INTEGER NOT NULL,
    CLIENTE_ID          INTEGER NOT NULL,
    DATA_ABERTURA       DATE NOT NULL,
    DATA_PREVISTA       DATE,
    DATA_FECHAMENTO     DATE,
    STATUS              VARCHAR(15) NOT NULL,
    DESCRICAO_PROBLEMA  VARCHAR(500),
    VALOR_TOTAL         NUMERIC(15,2) DEFAULT 0,
    FOTO                BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    MINIATURA           BLOB SUB_TYPE 0 SEGMENT SIZE 80
);

CREATE TABLE STATUS_LOG (
    ID                INTEGER NOT NULL,
    ORDEM_ID          INTEGER NOT NULL,
    DATA_HORA         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS_ANTERIOR   VARCHAR(15),
    STATUS_NOVO       VARCHAR(15) NOT NULL,
    USUARIO_SIMULADO  VARCHAR(50)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CLIENTE ADD PRIMARY KEY (ID);
ALTER TABLE ITEM_ORDEM ADD PRIMARY KEY (ID);
ALTER TABLE ORDEM_SERVICO ADD PRIMARY KEY (ID);
ALTER TABLE STATUS_LOG ADD PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ITEM_ORDEM ADD CONSTRAINT FK_ITEM_ORDEM FOREIGN KEY (ORDEM_ID) REFERENCES ORDEM_SERVICO (ID) ON DELETE CASCADE;
ALTER TABLE ORDEM_SERVICO ADD CONSTRAINT FK_OS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID);
ALTER TABLE STATUS_LOG ADD CONSTRAINT FK_STATUSLOG_OS FOREIGN KEY (ORDEM_ID) REFERENCES ORDEM_SERVICO (ID) ON DELETE CASCADE;


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX IDX_OS_CLIENTE ON ORDEM_SERVICO (CLIENTE_ID);
CREATE INDEX IDX_OS_DATA_ABERTURA ON ORDEM_SERVICO (DATA_ABERTURA);
CREATE INDEX IDX_OS_STATUS ON ORDEM_SERVICO (STATUS);
CREATE INDEX IDX_STATUSLOG_DATA ON STATUS_LOG (DATA_HORA);
CREATE INDEX IDX_STATUSLOG_ORDEM ON STATUS_LOG (ORDEM_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TRG_CLIENTE_BI */
CREATE TRIGGER TRG_CLIENTE_BI FOR CLIENTE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CLIENTE_ID, 1);
END
^

/* Trigger: TRG_ITEM_ORDEM_BI */
CREATE TRIGGER TRG_ITEM_ORDEM_BI FOR ITEM_ORDEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ITEM_ORDEM_ID, 1);
END
^

/* Trigger: TRG_ORDEM_SERVICO_BI */
CREATE TRIGGER TRG_ORDEM_SERVICO_BI FOR ORDEM_SERVICO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ORDEM_SERVICO_ID, 1);
END
^

/* Trigger: TRG_OS_AUDIT_STATUS */
CREATE TRIGGER TRG_OS_AUDIT_STATUS FOR ORDEM_SERVICO
ACTIVE AFTER UPDATE POSITION 0
AS
BEGIN
  /* Só grava no log se o status realmente mudou */
  IF (OLD.STATUS IS DISTINCT FROM NEW.STATUS) THEN
  BEGIN
    INSERT INTO STATUS_LOG (
      ORDEM_ID,
      STATUS_ANTERIOR,
      STATUS_NOVO,
      USUARIO_SIMULADO
    ) VALUES (
      NEW.ID,
      OLD.STATUS,
      NEW.STATUS,
      'SISTEMA' /* Aqui você pode passar um usuário padrão ou adaptar conforme sua aplicação */
    );
  END
END
^

/* Trigger: TRG_STATUS_LOG_BI */
CREATE TRIGGER TRG_STATUS_LOG_BI FOR STATUS_LOG
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_STATUS_LOG_ID, 1);
END
^

SET TERM ; ^

